name: merge test

on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:

jobs:
   merge-or-pr:
      runs-on: ubuntu-latest
      if: |
        github.event.pull_request.merged == true && 
        startsWith(github.event.pull_request.head.ref, 'hotfix/') && 
        github.event.pull_request.base.ref == 'acceptance'
      steps:
        - uses: actions/checkout@v1
          name: Checkout
        - uses: ./
          id: merge-or-pr
          with:
            target_branch: "development"
            sha_to_merge: ${{ github.event.pull_request.head.sha }}
            merge_branch_name: ${{ format('mergefix/{0}', github.event.pull_request.head.ref) }}
            pr_title: ${{ format('Merge fix of {0}', github.event.pull_request.head.ref) }}
            pr_maintainer_modification: "true"
            pr_draft: "true"
            pr_asignee: ${{ github.event.pull_request.user.login }}
            repo_token: ${{ secrets.GITHUB_TOKEN }} 
        - name: print-output
          run: echo "PR created ${{ steps.merge-or-pr.outputs.PR_CREATED  }} ${{ steps.merge-or-pr.outputs.PR_NUMBER }} ${{ steps.merge-or-pr.outputs.PR_URL }}"
        - uses: mshick/add-pr-comment@v1
          if: steps.merge-or-pr.PR_CREATED == 'false'
          with:
            message: |
              **Changes merged successfully to development**
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
            allow-repeats: false # This is the default
