name: merge test

on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:

jobs:
   merge-or-pr:
      runs-on: ubuntu-latest
      if: |
        github.event.pull_request.merged == true && 
        startsWith(github.event.pull_request.head.ref, 'hotfix/') && 
        github.event.pull_request.base.ref == 'acceptance'
      steps:
        - name: Merge or PR
          uses: siematypie/merge-or-pr@v1.0
          id: merge-or-pr
          with:
            target_branch: "development"
            sha_to_merge: ${{ github.event.pull_request.head.sha }}
            merge_branch_name: ${{ format('mergefix/{0}', github.event.pull_request.head.ref) }}
            pr_title: ${{ format('Merge fix of {0}', github.event.pull_request.head.ref) }}
            pr_maintainer_modification: true
            pr_draft: true
            pr_asignee: ${{ github.event.pull_request.user.login }}
            repo_token: ${{ secrets.GITHUB_TOKEN }} 
        - name: print-output
          run: echo "PR created ${{ steps.merge-or-pr.outputs.PR_CREATED  }} ${{ steps.merge-or-pr.outputs.PR_NUMBER }} ${{ steps.merge-or-pr.outputs.PR_URL }}"
        - uses: mshick/add-pr-comment@v1
          if: steps.merge-or-pr.outputs.PR_CREATED == 'false'
          with:
            message: |
              **Hotfix merged successfully to acceptance and development**
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            allow-repeats: false # This is the default
        - uses: mshick/add-pr-comment@v1
          if: steps.merge-or-pr.outputs.PR_CREATED == 'true'
          with:
            message: |
              **Hotfix merge to development failed**
              To fix it:
              > `git fetch && git checkout ${{ steps.merge-or-pr.outputs.MERGE_BRANCH_NAME }}`
              > `git pull origin development && git merge development` <- Resolve conflicts
              > `git push origin ${{ steps.merge-or-pr.outputs.MERGE_BRANCH_NAME }}`
              > Go to ${{ steps.merge-or-pr.outputs.PR_URL }} and choose a reviewer 
              > Merge changes 
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            allow-repeats: false # This is the default  
        
        
