on: 
  workflow_dispatch:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            
            const isOlderThanTwoHours = (pullRequest) => {
              const createdAt = Date.parse(pullRequest.created_at)
                const HOUR = 1000 * 60 * 60;
                const twoHoursAgo = Date.now() - HOUR * 2;
                return createdAt < twoHoursAgo;
            };
            
            const isMergeFix = (pullRequest) => {
              pullRequest.head.ref.startsWith('mergefix/');
            }
            
            console.log(context.repo.repo);
            console.log(context.repo.owner);
            const opts = github.pulls.list.endpoint.merge({
              state: 'open',
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const pulls = await github.paginate(opts);
            const validMergeFixes = pulls.filter(p => isMergeFix(p) && isOlderThanTwoHours(p))
            console.log(validMergeFixes);
