on: 
  workflow_dispatch:

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: getprs
        with:
          script: |
            
            const isOlderThanTwoHours = (pullRequest) => {
              const createdAt = Date.parse(pullRequest.created_at)
                const HOUR = 1000 * 60 * 60;
                const twoHoursAgo = Date.now() - HOUR * 2;
                return createdAt < twoHoursAgo;
            };
            
            const isMergeFix = (pullRequest) => 
             pullRequest.head.ref.startsWith('mergefix/');
            
            console.log(context.repo.repo);
            console.log(context.repo.owner);
            const opts = github.pulls.list.endpoint.merge({
              state: 'open',
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const pulls = await github.paginate(opts);
            const validMergeFixes = pulls
              .filter(p => isMergeFix(p) && isOlderThanTwoHours(p))
              .map(p => ({
                    {
                        color: "#36a64f",
                        author_name: p.assignee.login,
                        author_icon: p.assignee.url,
                        title: p.title,
                        title_link: p.html_url,
                        footer: "Created at",
                        ts: Math.floor(Date.parse(p.created_at) / 1000)
                    }
              }));
            if (validMergeFixes.length === 0) return;
            return validMergeFixes;
            
      - name: Send message to Slack API
        if: ${{steps.getprs.outputs.result != ''}}
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: C01GVMQ92PR
          slack-text: "Following mergefixes older than 2 hours needs to be resolved:"
          slack-optional-attachments: ${{steps.getprs.outputs.result}}
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
