# This is a basic workflow to help you get started with Actions

name: Slack

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slack-notifications:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - uses: actions/github-script@v4
        id: getpr
        with:
          script: |
             return [ 
                      {
                        color: "#36a64f",
                        author_name: "siematypie",
                        author_icon: "https://avatars.githubusercontent.com/u/22962539?v=4",
                        title: "PR Title",
                        title_link: "https://api.slack.com/",
                        footer: "Created at",
                        ts: 123456789
                    }
              ]
      - name: Get result
        run: echo "${{toJSON(steps.getpr.outputs.result)}}"
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: C01GVMQ92PR
          slack-optional-attachments: ${{steps.getpr.outputs.result}}
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
